const people = [
{name:"Delia Quiamas", table: 1, value:"Delia Quiamas", chair: 1},  
{name:"Robert Chapman", table: 1, value:"Robert Chapman", chair: 2},  
{name:"Alyssa Chapman", table: 1, value:"Alyssa Chapman", chair: 3},  
{name:"Ellis Chapman", table: 1, value:"Ellis Chapman", chair: 4},  
{name:"Jones Chapman", table: 1, value:"Jones Chapman", chair: 5},  
{name:"Jordan Chapman", table: 1, value:"Jordan Chapman", chair: 6},  
{name:"Valentina Quiamas", table: 1, value:"Valentina Quiamas", chair: 7},  
{name:"Majell	del	Castillo", table: 1, value:"Majell	del	Castillo", chair: 8},  

{name:"Marcelo Quiamas", table: 2, value:"Marcelo Quiamas",chair: 1},  
{name:"Venus Quiamas", table: 2, value:"Venus Quiamas", chair: 2},  
{name:"Samuel Edison Quiamas", table: 2, value:"Samuel Edison Quiamas", chair: 3},  
{name:"Megan Quiamas", table: 2, value:"Megan Quiamas", chair: 4},  
{name:"Raul Zamora", table: 2, value:"Raul Zamora", chair: 5},  
{name:"Chelo Gelacio", table: 2, value:"Chelo Gelacio", chair: 6},  
{name:"Floyd Gelacio", table: 2, value:"Floyd Gelacio", chair: 7},  

{name:"Shanelle Fae Quiamas", table: 3, value:"Shanelle Fae Quiamas", chair: 1},  
{name:"Abigail Dionisio", table: 3, value:"Abigail Dionisio", chair: 2},  
{name:"Elizabeth Spinney", table: 3, value:"Elizabeth Spinney", chair: 3},  
{name:"Ardelina A. Quiamas", table: 3, value:"Ardelina A. Quiamas", chair: 4},  
{name:"Felix Quiamas", table: 3, value:"Felix Quiamas", chair: 5},  
{name:"Raquel De La Cruz", table: 3, value:"Raquel De La Cruz", chair: 6},  
{name:"Jerome De La Cruz", table: 3, value:"Jerome De La Cruz", chair: 7},  
{name:"Anne Michelle De La Cruz ", table: 3, value:"Anne Michelle De La Cruz", chair: 8},  
{name:"Mario Orlino", table: 3, value:"Mario Orlino", chair: 9}, 
{name:"Ellen Orlino", table: 3, value:"Ellen Orlino", chair: 10}, 

{name:"Brian Meyer", table: 4, value:"Brian Meyer", chair: 1},  
{name:"Mary Meyer", table: 4, value:"Mary Meyer", chair: 2},  
{name:"Jacob Meyer", table: 4, value:"Jacob Meyer", chair: 3},  
{name:"Mikael Meyer", table: 4, value:"Mikael Meyer", chair: 4},  
{name:"Daniel Neumann", table: 4, value:"Daniel Neumann", chair: 5},  
{name:"Brady Mussmann", table: 4, value:"Brady Mussmann", chair: 6},  
{name:"Seth	Meyer", table: 4, value:"Seth	Meyer", chair: 7},  
{name:"Hillary	Meyer", table: 4, value:"Hillary	Meyer", chair: 8},  

{name:"Jordan Meyer", table: 5, value:"Jordan Meyer", chair: 1},  
{name:"Meridith	Meyer", table: 5, value:"Meridith	Meyer", chair: 2},  
{name:"Ben Meyer", table: 5, value:"Ben Meyer", chair: 3},  
{name:"McKenzie Kolbe", table: 5, value:"McKenzie Kolbe", chair: 4},  
{name:"Joshua Meyer", table: 5, value:"Joshua Meyer", chair: 5},  
{name:"Grant Elsbernd", table: 5, value:"Grant Elsbernd", chair: 6},  
{name:"Nathan Meyer", table: 5, value:"Nathan Meyer", chair: 7}, 
{name:"Matthew Meyer", table: 5, value:"Matthew Meyer", chair: 8}, 

{name:"Susan Griffin", table: 6, value:"Susan Griffin", chair: 1},  
{name:"Ron Griffin", table: 6, value:"Ron Griffin", chair: 2},  
{name:"Charity Griffin", table: 6, value:"Charity Griffin", chair: 3},  
{name:"Chance Griffin", table: 6, value:"Chance Griffin", chair: 4},  
{name:"Chantal Mendoza", table: 6, value:"Chantal Mendoza", chair: 5},  
{name:"Christine Barajas", table: 6, value:"Christine Barajas", chair: 6},  
{name:"Raymond Barajas", table: 6, value:"Raymond Barajas", chair: 7},  
{name:"Christian Barajas", table: 6, value:"Christian Barajas", chair: 8},  
{name:"Sean Barajas", table: 6, value:"Sean Barajas", chair: 9}, 
{name:"Simplicio Quiamas", table: 6, value:"Simplicio Quiamas", chair: 10},

{name:"Danny Nguyen", table: 7, value:"Danny Nguyen", chair: 1},  
{name:"Kristine Pham", table: 7, value:"Kristine Pham", chair: 2},  
{name:"Michelle Phan-Tang", table: 7, value:"Michelle Phan-Tang", chair: 3},  
{name:"Jesse Phan", table: 7, value:"Jesse Phan", chair: 4},  
{name:"Truongson Nguyen", table: 7, value:"Truongson Nguyen", chair: 5},  
{name:"Connie De Guzman", table: 7, value:"Connie De Guzman", chair: 6},  
{name:"Diane Padre-Gozun", table: 7, value:"Diane Padre-Gozun", chair: 7},  
{name:"Allen-Brian Gozun", table: 7, value:"Allen-Brian Gozun", chair: 8},  
{name:"Vera Vanderkaan", table: 7, value:"Vera Vanderkaan", chair: 9}, 

{name:"Valerie Liebhaber", table: 8, value:"Valerie Liebhaber", chair: 1},  
{name:"Andrea Liebhaber", table: 8, value:"Andrea Liebhaber", chair: 2},  
{name:"Marlene Sanchez", table: 8, value:"Marlene Sanchez", chair: 3},  
{name:"Robert Benavides", table: 8, value:"Robert Benavides", chair: 4},  
{name:"Lawrence Monson", table: 8, value:"Lawrence Monson", chair: 5},  
{name:"Trevor Graifman", table: 8, value:"Trevor Graifman", chair: 6},  
{name:"Jessica Costales-Cantrell", table: 8, value:"Jessica Costales-Cantrell", chair: 7},  
{name:"Chris Cantrell", table: 8, value:"Chris Cantrell", chair: 8},  
{name:"Nathan Batuyong", table: 8, value:"Nathan Batuyong", chair: 9}, 
{name:"Melissa	Martinez", table: 8, value:"Melissa	Martinez", chair: 10}, 

{name:"Rose Cua Watts", table: 9, value:"Rose Cua Watts", chair: 1},  
{name:"Loren Watts", table: 9, value:"Loren Watts", chair: 2},  
{name:"Kimberlyn Watts", table: 9, value:"Kimberlyn Watts", chair: 3},  
{name:"Arnelda LuzViminda Cua", table: 9, value:"Arnelda LuzViminda Cua", chair: 4},  
{name:"Evelyn Mateo", table: 9, value:"Evelyn Mateo", chair: 5},  
{name:"Honesto	Mateo", table: 9, value:"Honesto	Mateo", chair: 6},  
{name:"Dianne Carambas", table: 9, value:"Dianne Carambas", chair: 7},  
{name:"Hazel Mateo", table: 9, value:"Hazel	Mateo", chair: 8},  
{name:"Miguel	Francis	Mateo", table: 9, value:"Miguel	Francis	Mateo", chair: 9},  
{name:"Albert	Jacob	Mateo", table: 9, value:"Albert	Jacob	Mateo", chair: 10},  

{name:"June Banks", table: 10, value:"June Banks", chair: 1},  
{name:"Tracey Banks", table: 10, value:"Tracey Banks", chair: 2},  
{name:"Connie Kolat", table: 10, value:"Connie Kolat", chair: 3},  
{name:"Lauren Kolat", table: 10, value:"Lauren Kolat", chair: 4},  
{name:"Lori Krueger", table: 10, value:"Lori Krueger", chair: 5},  
{name:"Marissa Ritter", table: 10, value:"Marissa Ritter", chair: 6},  
{name:"Anastacia	Rodriguez", table: 10, value:"Anastacia	Rodriguez", chair: 7},  
{name:"Michael	Conejo", table: 10, value:"Michael	Conejo", chair: 8},  
{name:"Michelle	Yim	Tang", table: 10, value:"Michelle	Yim	Tang", chair: 9},  
{name:"Kenneth	Tang", table: 10, value:"Kenneth	Tang", chair: 10}, 

{name:"Karen	Botardo	Palagnas", table: 15, value:"Karen	Botardo	Palagnas", chair: 1},  
{name:"JanRay	Palagnas", table: 11, value:"JanRay	Palagnas", chair: 2},  
{name:"Urey Chow", table: 11, value:"Urey Chow", chair: 3},  
{name:"Shardale McAfee", table: 11, value:"Shardale McAfee", chair: 4},  
{name:"Cynterrial McAfee", table: 11, value:"Cynterrial McAfee", chair: 5},  
{name:"Richmond Ramirez", table: 11, value:"Richmond Ramirez", chair: 6},  
{name:"Jeffrey Sheehan", table: 11, value:"Jeffrey Sheehan", chair: 7},  
{name:"Ynigo Ramirez", table: 11, value:"Ynigo Ramirez", chair: 8},  
{name:"Daisy	Wang", table: 11, value:"Daisy	Wang", chair: 9},  
{name:"Betsy	Gast", table: 11, value:"Betsy	Gast", chair: 10}, 

{name:"Dario Quiamas", table: 12, value:"Dario Quiamas", chair: 1},  
{name:"Agnes Quiamas", table: 12, value:"Agnes Quiamas", chair: 2},  
{name:"Anthony Quiamas", table: 12, value:"Anthony Quiamas", chair: 3},  
{name:"Nevada Quiamas", table: 12, value:"Nevada Quiamas", chair: 4},  
{name:"Justice Quiamas ", table: 12, value:"Justice Quiamas", chair: 5},  
{name:"Eleonor Loresca", table: 12, value:"Eleonor Loresca", chair: 6},
{name:"Chassidy	Turalva-Albano", table: 11, value:"Chassidy	Turalva-Albano", chair: 7},  
{name:"Jacqueline	Chan", table: 11, value:"Jacqueline	Chan", chair: 8},  
{name:"London	Puon", table: 11, value:"London	Puon", chair: 9},  

{name:"Rhona Sanchez", table: 14, value:"Rhona Sanchez", chair: 1},  
{name:"Samuel Sanchez", table: 14, value:"Samuel Sanchez", chair: 2},  
{name:"Zjei Sanchez", table: 14, value:"Zjei Sanchez", chair: 3},  
{name:"Wynzhiel Sanchez", table: 14, value:"Wynzhiel Sanchez", chair: 4},  
{name:"Liwliwa	Neflas", table: 14, value:"Liwliwa	Neflas", chair: 5},  
{name:"Clemence Neflas", table: 14, value:"Clemence Neflas", chair: 6},  
{name:"Kyle Neflas", table: 14, value:"Kyle Neflas", chair: 7},  
{name:"Dylan Neflas", table: 14, value:"Dylan Neflas", chair: 8}, 

{name:"Kathleen Orfanel", table: 15, value:"Kathleen Orfanel", chair: 1},  
{name:"Elrick Orfanel", table: 15, value:"Elrick Orfanel", chair: 2},  
{name:"Raymond Truong", table: 15, value:"Raymond Truong", chair: 3},  
{name:"Kyle Brown", table: 15, value:"Kyle Brown", chair: 4},  
{name:"Karrie Lau", table: 15, value:"Karrie Lau", chair: 5},  
{name:"Marinelle Camillon", table: 15, value:"Marinelle Camillon", chair: 6}, 
{name:"Steven	Loo", table: 15, value:"Steven	Loo", chair: 7},  
{name:"Christine	Thorntorn", table: 15, value:"Christine	Thorntorn", chair: 8},  
{name:"Daryl	Evalobo", table: 15, value:"Daryl	Evalobo", chair: 9},   

{name:"Lenie Siahaan", table: 16, value:"Lenie Siahaan", chair: 1},  
{name:"Tommy Siahaan", table: 16, value:"Tommy Siahaan", chair: 2},  
{name:"Lynette Siahaan", table: 16, value:"Lynette Siahaan", chair: 3},  
{name:"Tamara Siahaan", table: 16, value:"Tamara Siahaan", chair: 4},  
{name:"Redford Barrientos", table: 16, value:"Redford Barrientos", chair: 5}, 
{name:"Ivy	Siahaan", table: 16, value:"Ivy	Siahaan", chair: 7},  
{name:"Beatrice	Augustine", table: 16, value:"Beatrice	Augustine", chair: 8},  
{name:"Kris	Cacal", table: 16, value:"Kris	Cacal", chair: 9},   

{name:"Kenneth Salvador", table: 17, value:"Kenneth Salvador", chair: 1},  
{name:"Carol Quiamas", table: 17, value:"Carol Quiamas", chair: 2},  
{name:"Darrel Jude Quiamas", table: 17, value:"Darrel Jude Quiamas", chair: 3},  
{name:"Shella Mae Quiamas", table: 17, value:"Shella Mae Quiamas", chair: 4},  
{name:"Jonathan Hedgecorth", table: 17, value:"Jonathan Hedgecorth", chair: 5},  
{name:"Kiana Reyes", table: 17, value:"Kiana Reyes", chair: 6},  
{name:"Kristen Reyes", table: 17, value:"Kristen Reyes", chair: 7},  
{name:"Julian Reyes", table: 17, value:"Julian Reyes", chair: 8},  
{name:"Dean Quiamas Agcaoili", table: 17, value:"Dean Quiamas Agcaoili", chair: 9}, 

{name:"Emma Quiamas", table: 18, value:"Emma Quiamas", chair: 1},  
{name:"Rupenio Quiamas", table: 18, value:"Rupenio Quiamas", chair: 2},  
{name:"Tina Carlos", table: 18, value:"Tina Carlos", chair: 3},  
{name:"Gena Carlos ", table: 18, value:"Gena Carlos", chair: 4},  
{name:"Samantha Carlos", table: 18, value:"Samantha Carlos", chair: 5},  
{name:"Elijah Carlos", table: 18, value:"Elijah Carlos", chair: 6},  
{name:"Bella Fangonil", table: 18, value:"Bella Fangonil", chair: 7},  

]

export default people