const people = [
{name:"Shanelle Fae Quiamas", table: 1, value:"Shanelle Fae Quiamas", chair: 1},  
{name:"Abigail Dionisio", table: 1, value:"Abigail Dionisio", chair: 2},  
{name:"Elizabeth Spinney", table: 1, value:"Elizabeth Spinney", chair: 3},  
{name:"Ardelina A. Quiamas", table: 1, value:"Ardelina A. Quiamas", chair: 4},  
{name:"Felix Quiamas", table: 1, value:"Felix Quiamas", chair: 5},  
{name:"Raquel De La Cruz", table: 1, value:"Raquel De La Cruz", chair: 6},  
{name:"Jerome De La Cruz", table: 1, value:"Jerome De La Cruz", chair: 7},  
{name:"Anne Michelle De La Cruz ", table: 1, value:"Anne Michelle De La Cruz", chair: 8},  
{name:"Mario Orlino", table: 1, value:"Mario Orlino", chair: 9}, 
{name:"Ellen Orlino", table: 1, value:"Ellen Orlino", chair: 10}, 

{name:"Marcelo Quiamas", table: 2, value:"Marcelo Quiamas",chair: 1},  
{name:"Venus Quiamas", table: 2, value:"Venus Quiamas", chair: 2},  
{name:"Samuel Edison Quiamas", table: 2, value:"Samuel Edison Quiamas", chair: 3},  
{name:"Megan Quiamas", table: 2, value:"Megan Quiamas", chair: 4},  
{name:"Raul Zamora", table: 2, value:"Raul Zamora", chair: 5},  
{name:"Chelo Gelacio", table: 2, value:"Chelo Gelacio", chair: 6},  
{name:"Floyd Gelacio", table: 2, value:"Floyd Gelacio", chair: 7},  

{name:"Delia Quiamas", table: 3, value:"Delia Quiamas", chair: 1},  
{name:"Robert Chapman", table: 3, value:"Robert Chapman", chair: 2},  
{name:"Alyssa Chapman", table: 3, value:"Alyssa Chapman", chair: 3},  
{name:"Ellis Chapman", table: 3, value:"Ellis Chapman", chair: 4},  
{name:"Jones Chapman", table: 3, value:"Jones Chapman", chair: 5},  
{name:"Jordan Chapman", table: 3, value:"Jordan Chapman", chair: 6},  
{name:"Valentina Quiamas", table: 3, value:"Valentina Quiamas", chair: 7},  

{name:"Emma Quiamas", table: 4, value:"Emma Quiamas", chair: 1},  
{name:"Rupenio Quiamas", table: 4, value:"Rupenio Quiamas", chair: 2},  
{name:"Tina Carlos", table: 4, value:"Tina Carlos", chair: 3},  
{name:"Gena Carlos ", table: 4, value:"Gena Carlos", chair: 4},  
{name:"Samantha Carlos", table: 4, value:"Samantha Carlos", chair: 5},  
{name:"Elijah Carlos", table: 4, value:"Elijah Carlos", chair: 6},  
{name:"Bella Fangonil", table: 4, value:"Bella Fangonil", chair: 7},  

{name:"Susan Griffin", table: 5, value:"Susan Griffin", chair: 1},  
{name:"Ron Griffin", table: 5, value:"Ron Griffin", chair: 2},  
{name:"Charity Griffin", table: 5, value:"Charity Griffin", chair: 3},  
{name:"Chance Griffin", table: 5, value:"Chance Griffin", chair: 4},  
{name:"Chantal Mendoza", table: 5, value:"Chantal Mendoza", chair: 5},  
{name:"Christine Barajas", table: 5, value:"Christine Barajas", chair: 6},  
{name:"Raymond Barajas", table: 5, value:"Raymond Barajas", chair: 7},  
{name:"Christian Barajas", table: 5, value:"Christian Barajas", chair: 8},  
{name:"Sean Barajas", table: 5, value:"Sean Barajas", chair: 9}, 
{name:"Simplicio Quiamas", table: 5, value:"Simplicio Quiamas", chair: 10}, 

{name:"Rose Cua Watts", table: 6, value:"Rose Cua Watts", chair: 1},  
{name:"Loren Watts", table: 6, value:"Loren Watts", chair: 2},  
{name:"Kimberlyn Watts", table: 6, value:"Kimberlyn Watts", chair: 3},  
{name:"Arnelda LuzViminda Cua", table: 6, value:"Arnelda LuzViminda Cua", chair: 4},  
{name:"Evelyn Mateo", table: 6, value:"Evelyn Mateo", chair: 5},  
{name:"Honesty Mateo", table: 6, value:"Honesty Mateo", chair: 6},  
{name:"Dianne Carambas", table: 6, value:"Dianne Carambas", chair: 7},  
{name:"Hazel Mateo", table: 6, value:"Hazel Mateo", chair: 8},  

{name:"Kenneth Salvador", table: 7, value:"Kenneth Salvador", chair: 1},  
{name:"Carol Quiamas", table: 7, value:"Carol Quiamas", chair: 2},  
{name:"Darrel Jude Quiamas", table: 7, value:"Darrel Jude Quiamas", chair: 3},  
{name:"Shella Mae Quiamas", table: 7, value:"Shella Mae Quiamas", chair: 4},  
{name:"Jonathan Hedgecorth", table: 7, value:"Jonathan Hedgecorth", chair: 5},  
{name:"Kiana Reyes", table: 7, value:"Kiana Reyes", chair: 6},  
{name:"Kristen Reyes", table: 7, value:"Kristen Reyes", chair: 7},  
{name:"Julian Reyes", table: 7, value:"Julian Reyes", chair: 8},  
{name:"Dean Quiamas Agcaoili", table: 7, value:"Dean Quiamas Agcaoili", chair: 9}, 

{name:"Rhona Sanchez", table: 8, value:"Rhona Sanchez", chair: 1},  
{name:"Samuel Sanchez", table: 8, value:"Samuel Sanchez", chair: 2},  
{name:"Zjei Sanchez", table: 8, value:"Zjei Sanchez", chair: 3},  
// {name:"Shella Mae Quiamas", table: 8, value:"Shella Mae Quiamas", chair: 4},  
// {name:"Jonathan Hedgecorth", table: 8, value:"Jonathan Hedgecorth", chair: 5},  
{name:"Wynzhiel Sanchez", table: 8, value:"Wynzhiel Sanchez", chair: 6},  
{name:"Clemence Neflas", table: 8, value:"Clemence Neflas", chair: 7},  
{name:"Kyle Neflas", table: 8, value:"Kyle Neflas", chair: 8},  
{name:"Dylan Neflas", table: 8, value:"Dylan Neflas", chair: 9}, 

{name:"Dario Quiamas", table: 9, value:"Dario Quiamas", chair: 1},  
{name:"Agnes Quiamas", table: 9, value:"Agnes Quiamas", chair: 2},  
{name:"Anthony Quiamas", table: 9, value:"Anthony Quiamas", chair: 3},  
{name:"Nevada Quiamas", table: 9, value:"Nevada Quiamas", chair: 4},  
{name:"Justice Quiamas ", table: 9, value:"Justice Quiamas", chair: 5},  
{name:"Eleonor Loresca", table: 9, value:"Eleonor Loresca", chair: 6},


{name:"Valerie Liebhaber", table: 10, value:"Valerie Liebhaber", chair: 1},  
{name:"Andrea Liebhaber", table: 10, value:"Andrea Liebhaber", chair: 2},  
{name:"Marlene Sanchez", table: 10, value:"Marlene Sanchez", chair: 3},  
{name:"Robert Benavides", table: 10, value:"Robert Benavides", chair: 4},  
{name:"Lawrence Monson", table: 10, value:"Lawrence Monson", chair: 5},  
{name:"Trevor Graifman", table: 10, value:"Trevor Graifman", chair: 6},  
{name:"Jessica Costales-Cantrell", table: 10, value:"Jessica Costales-Cantrell", chair: 7},  
{name:"Chris Cantrell", table: 10, value:"Chris Cantrell", chair: 8},  
{name:"Nathan Batuyong", table: 10, value:"Nathan Batuyong", chair: 9}, 
{name:"Angelica Pena", table: 10, value:"Angelica Pena", chair: 10}, 

{name:"Danny Nguyen", table: 11, value:"Danny Nguyen", chair: 1},  
{name:"Kristine Pham", table: 11, value:"Kristine Pham", chair: 2},  
{name:"Michelle Phan-Tang", table: 11, value:"Michelle Phan-Tang", chair: 3},  
{name:"Jesse Phan", table: 11, value:"Jesse Phan", chair: 4},  
{name:"Truongson Nguyen", table: 11, value:"Truongson Nguyen", chair: 5},  
{name:"Connie De Guzman", table: 11, value:"Connie De Guzman", chair: 6},  
{name:"Diane Padre-Gozun", table: 11, value:"Diane Padre-Gozun", chair: 7},  
{name:"Allen-Brian Gozun", table: 11, value:"Allen-Brian Gozun", chair: 8},  
{name:"Vera Vanderkaan", table: 11, value:"Vera Vanderkaan", chair: 9}, 
{name:"Chris Millbern", table: 11, value:"Chris Millbern", chair: 10}, 

{name:"Jordan Meyer", table: 12, value:"Jordan Meyer", chair: 1},  
{name:"Meredith Meyer", table: 12, value:"Meredith Meyer", chair: 2},  
{name:"Seth Meyer", table: 12, value:"Seth Meyer", chair: 3},  
{name:"Hillary Meyer", table: 12, value:"Hillary Meyer", chair: 4},  
{name:"Ben Meyer", table: 12, value:"Ben Meyer", chair: 5},  
{name:"McKenzie Kolbe", table: 12, value:"McKenzie Kolbe", chair: 6},  
{name:"Joshua Meyer", table: 12, value:"Joshua Meyer", chair: 7},  
{name:"Grant Elsbernd", table: 12, value:"Grant Elsbernd", chair: 8},  
{name:"Nathan Meyer", table: 12, value:"Nathan Meyer", chair: 9}, 
{name:"Matthew Meyer", table: 12, value:"Matthew Meyer", chair: 10}, 

{name:"Brian Meyer", table: 14, value:"Brian Meyer", chair: 1},  
{name:"Mary Meyer", table: 14, value:"Mary Meyer", chair: 2},  
{name:"Jacob Meyer", table: 14, value:"Jacob Meyer", chair: 3},  
{name:"Mikael Meyer", table: 14, value:"Mikael Meyer", chair: 4},  
{name:"Daniel Neumann", table: 14, value:"Daniel Neumann", chair: 5},  
{name:"Brady Mussmann", table: 14, value:"Brady Mussmann", chair: 6},  
{name:"Daisy Wang", table: 14, value:"Daisy Wang", chair: 7},  
{name:"Betsy Gast", table: 14, value:"Betsy Gast", chair: 8},  

{name:"Kathleen Orfanel", table: 15, value:"Kathleen Orfanel", chair: 1},  
{name:"Elrick Orfanel", table: 15, value:"Elrick Orfanel", chair: 2},  
{name:"Raymond Truong", table: 15, value:"Raymond Truong", chair: 3},  
{name:"Kyle Brown", table: 15, value:"Kyle Brown", chair: 4},  
{name:"Karrie Lau", table: 15, value:"Karrie Lau", chair: 5},  
{name:"Marinelle Camillon", table: 15, value:"Marinelle Camillon", chair: 6},  

{name:"June Banks", table: 16, value:"June Banks", chair: 1},  
{name:"Tracey Banks", table: 16, value:"Tracey Banks", chair: 2},  
{name:"Connie Kolat", table: 16, value:"Connie Kolat", chair: 3},  
{name:"Lauren Kolat", table: 16, value:"Lauren Kolat", chair: 4},  
{name:"Lori Krueger", table: 16, value:"Lori Krueger", chair: 5},  
{name:"Marissa Ritter", table: 16, value:"Marissa Ritter", chair: 6},  

{name:"Richmond Ramirez", table: 17, value:"Richmond Ramirez", chair: 1},  
{name:"Jeffrey Sheehan", table: 17, value:"Jeffrey Sheehan", chair: 2},  
{name:"Ynigo Ramirez", table: 17, value:"Ynigo Ramirez", chair: 3},  
{name:"Urey Chow", table: 17, value:"Urey Chow", chair: 4},  
{name:"Shardale McAfee", table: 17, value:"Shardale McAfee", chair: 5},  
{name:"Cynterrial McAfee", table: 17, value:"Cynterrial McAfee", chair: 6},  

{name:"Lenie Siahaan", table: 18, value:"Lenie Siahaan", chair: 1},  
{name:"Tommy Siahaan", table: 18, value:"Tommy Siahaan", chair: 2},  
{name:"Lynette Siahaan", table: 18, value:"Lynette Siahaan", chair: 3},  
{name:"Tamara Siahaan", table: 18, value:"Tamara Siahaan", chair: 4},  
{name:"Redford Barrientos", table: 18, value:"Redford Barrientos", chair: 5},  

]

export default people